// <auto-generated />
namespace Casgem_CodeFirstProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_add_relation_guide_socialmedia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_add_relation_guide_socialmedia));
        
        string IMigrationMetadata.Id
        {
            get { return "202307120808435_mig_add_relation_guide_socialmedia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
